# Generated by Django 4.2 on 2023-06-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.ImageField(blank=True, default='listings/free-icon-online-learning-2436874.png', null=True, upload_to='listings/'),
        ),
    ]
