# Generated by Django 4.2 on 2023-04-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_university',
            field=models.BooleanField(default=False),
        ),
    ]
