# Generated by Django 4.2 on 2023-05-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_staffuser_teacheruser_universityuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
