# Generated by Django 4.2 on 2023-06-04 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_profile_teacherprofile_universityprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('options', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(choices=[('B', 'Bachelor'), ('M', 'Master'), ('P', 'Ph.D.'), ('O', 'Other')], max_length=1)),
                ('experience', models.PositiveIntegerField()),
                ('skills', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('exam_questions', models.ManyToManyField(to='users.examquestion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
